# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-10 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_number', models.CharField(max_length=17, verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0439 \u0442\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('additional_number', models.CharField(max_length=17, verbose_name='\u0414\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u044b\u0439 \u0442\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043c\u0430\u0433\u0430\u0437\u0438\u043d\u0430')),
                ('about_descript', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('address', models.CharField(max_length=500, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0441 \u043e\u0444\u0438\u0441\u0430')),
                ('email', models.EmailField(max_length=254, verbose_name='\u0410\u0434\u0440\u0435\u0441\u0441 \u044d\u043b\u0435\u043a\u0442\u0440\u043e\u043d\u043d\u043e\u0439 \u043f\u043e\u0447\u0442\u044b')),
                ('vk_url', models.URLField(max_length=500, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0433\u0440\u0443\u043f\u043f\u0443 VK')),
                ('instagram_url', models.URLField(max_length=500, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 Instagram')),
                ('twitter_url', models.URLField(max_length=500, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 Twitter')),
                ('fb_url', models.URLField(max_length=500, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0433\u0440\u0443\u043f\u043f\u0443 Facebook')),
                ('active', models.BooleanField(default=False, verbose_name='\u0410\u043a\u0442\u0438\u0432\u043d\u043e\u0441\u0442\u044c \u043f\u0440\u043e\u0444\u0438\u043b\u044f')),
            ],
            options={
                'verbose_name': '\u043f\u0440\u043e\u0444\u0438\u043b\u044c',
                'verbose_name_plural': '\u041e\u0441\u043d\u043e\u0432\u043d\u044b\u0435 \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438',
            },
        ),
    ]
