# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-23 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_items_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='car',
            new_name='item',
        ),
    ]
