# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-23 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170823_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='\u0421\u043a\u0438\u0434\u043a\u0430 (0 - \u0431\u0435\u0437 \u0441\u043a\u0438\u0434\u043a\u0438)'),
        ),
    ]
