# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-24 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170824_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TypesRooms', verbose_name='\u041f\u043e\u043c\u0435\u0449\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='items',
            name='cost_of',
            field=models.IntegerField(default=0, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0442\u043e\u0432\u0430\u0440\u0430 (\u0440\u0443\u0431)'),
        ),
    ]
