# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-05 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_items_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='random_discount',
            field=models.IntegerField(default=5, verbose_name='\u0421\u043b\u0443\u0447\u0430\u0439\u043d\u044b\u0445 \u043e\u0431\u044a\u0435\u043a\u0442\u043e\u0432 \u0441\u043e \u0441\u043a\u0438\u0434\u043a\u043e\u0439'),
        ),
    ]
