# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-05 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_settings_random_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='hit_count',
            field=models.IntegerField(default=5, verbose_name='\u0425\u0438\u0442\u043e\u0432 \u043f\u0440\u043e\u0434\u0430\u0436'),
        ),
    ]
