# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-27 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170825_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': '\u043f\u043e\u0434\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f', 'verbose_name_plural': '\u0421\u043f\u0438\u0441\u043e\u043a \u043f\u043e\u0434\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0439'},
        ),
        migrations.AlterModelOptions(
            name='typesrooms',
            options={'verbose_name': '\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f', 'verbose_name_plural': '\u0421\u043f\u0438\u0441\u043e\u043a \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0439'},
        ),
        migrations.AddField(
            model_name='categories',
            name='data_id',
            field=models.IntegerField(default=0, verbose_name='\u0410\u0442\u0442\u0440\u0438\u0431\u0443\u0442 data_id \u0432 html'),
        ),
        migrations.AddField(
            model_name='typesrooms',
            name='data_id',
            field=models.IntegerField(default=0, verbose_name='\u0410\u0442\u0442\u0440\u0438\u0431\u0443\u0442 data_id \u0432 html'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=25, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043f\u043e\u0434\u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TypesRooms', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='typesrooms',
            name='name',
            field=models.CharField(max_length=25, verbose_name='\u041d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435 \u043a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u0438'),
        ),
    ]
